name: Deploy Go App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app-binary main.go
      
      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCA_KEY }}
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      # ðŸ”¥ Step baru: create folder di VM kalau belum ada
      - name: Prepare directory on VM
        run: |
          gcloud compute ssh ${{ secrets.GCE_INSTANCE }} \
            --zone=${{ secrets.GCE_INSTANCE_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="mkdir -p ~/app"

      - name: Upload Binary to GCE
        run: |
          gcloud compute scp app-binary \
            ${{ secrets.GCE_INSTANCE }}:~/app/app-binary \
            --zone=${{ secrets.GCE_INSTANCE_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }}
      
      - name: Deploy and Restart Service
        run: |
          run: |
          gcloud compute ssh ${{ secrets.GCE_INSTANCE }} \
            --zone=${{ secrets.GCE_INSTANCE_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="
              pkill -f ~/app/app-binary || true &&
              nohup ~/app/app-binary > ~/app/app.log 2>&1 &
              echo 'App started successfully'
            "
